name: Build backend container
on:
  push:
    paths:
      - 'backend/*'
  workflow_dispatch:

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2
         with:
           ref: main
           path: './backend'

       - name: Build and Publish head Docker image
         uses: VaultVulp/gp-docker-action@1.2.0
         with:
           github-token: ${{ secrets.GITHUB_TOKEN }} 
           image-name: veritas_backend_pocketbase
           dockerfile: Dockerfile
           image-tag: latest 
