name: Build backend container
on:
  workflow_run:
    workflows: ["Shellcheck on Scripts"]
    branches: [main]
    types: 
      - completed

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2
       
       - name: Build and Publish head Docker image
         uses: VaultVulp/gp-docker-action@1.6.0
         with:
           github-token: ${{ secrets.GITHUB_TOKEN }} 
           image-name: veritas_backend_pocketbase
           build-context: ./backend
           image-tag: latest
